### PR TITLE
fix: clean up connection handler if connection fails

### LINKED ISSUE #3402: Out of memory error
**Version:**
PGAdapter >= 0.48.0

**Problem Description:**
During operation, PGAdapter exhibits a memory leak: heap usage gradually increases, eventually leading to a `java.lang.OutOfMemoryError: Java heap space`. After this, the process either terminates (if the `-XX:+ExitOnOutOfMemoryError` flag is set) or hangs and stops proxying requests, although port `5432` remains open.

**Expected Behavior:**
Memory usage should remain stable under normal load, and there should be no memory leaks.

**Actual Behavior:**
Memory usage gradually increases, resulting in an `OutOfMemoryError`.

**Steps to Reproduce:**

Start PGAdapter >= 0.48.0
Connect clients and perform standard queries to the database through the proxy.
Monitor the process’s memory usage.
Wait for the `OutOfMemoryError` to occur.

**Additional Information:**

With the -`XX:+ExitOnOutOfMemoryError` flag, the process terminates immediately after the OutOfMemoryError.
Without this flag, the process hangs, the port remains open, but requests are not proxied.

**App manifest:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-service
    environment: beta
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-service
      environment: beta
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-service
        environment: beta
    spec:
      containers:
      - command:
        - sh
        - -c
        - set -e; until pg_isready -h localhost -p 5432 -q; do sleep 1; done; entrypoints/run
        env:
        - name: POSTGRESQL_DSN
          value: postgresql://localhost:5432/my-database?pool_max_conns=50
        image: us-east1-docker.pkg.dev/my-project/my-repo/my-service:d4214a8
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: backend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 1Gi
      - args:
        - -p=my-project
        - -i=my-instance
        - -d=my-database
        - -r=minSessions=50;maxSessions=100;numChannels=8
        - -x
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -Xmx768m -XX:+ExitOnOutOfMemoryError
        image: gcr.io/cloud-spanner-pg-adapter/pgadapter:v0.48.0
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 5
        name: pgadapter
        ports:
        - containerPort: 5432
          name: tcp
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 1Gi
```
**Logs** with `-XX:+ExitOnOutOfMemoryError`:
```
INFO 2025-06-03T07:47:02.432298968Z [resource.labels.containerName: pgadapter] java -jar pgadapter.jar -p=my-project -i=my-instance -d=my-database -r=minSessions=50;maxSessions=100;numChannels=8 -x
ERROR 2025-06-03T07:47:03.164974125Z [resource.labels.containerName: pgadapter] Picked up JAVA_TOOL_OPTIONS: -Xmx768m -XX:+ExitOnOutOfMemoryError
INFO 2025-06-03T07:47:09.778482675Z [resource.labels.containerName: pgadapter] -- Starting PGAdapter version 0.48.0 --
INFO 2025-06-03T07:47:12.149459757Z [resource.labels.containerName: pgadapter] -- PostgreSQL version: 14.1 --
ERROR 2025-06-03T07:47:12.476494197Z [resource.labels.containerName: pgadapter] {}
INFO 2025-06-03T07:47:12.797198343Z [resource.labels.containerName: pgadapter] [2025-06-03 07:47:12.743] [INFO] (com.google.cloud.spanner.pgadapter.ProxyServer startServer): Server started on port 5432
INFO 2025-06-03T07:47:12.814548958Z [resource.labels.containerName: pgadapter] [2025-06-03 07:47:12.811] [INFO] (com.google.cloud.spanner.pgadapter.ConnectionHandler setThread): Connection handler with ID ConnectionHandler-0 created for client 127.0.0.1

... few moments later

INFO 2025-06-03T22:56:10.783852566Z [resource.labels.containerName: pgadapter] [2025-06-03 22:56:10.783] [INFO] (com.google.cloud.spanner.pgadapter.ConnectionHandler run): [ConnectionHandler-10919]: [Run] Connection handler with ID ConnectionHandler-10919 starting for client 127.0.0.1 with thread Thread[#16493,ConnectionHandler-10919,5,main]
INFO 2025-06-03T22:56:11.133948503Z [resource.labels.containerName: pgadapter] Terminating due to java.lang.OutOfMemoryError: Java heap space

... then restarts

INFO 2025-06-03T22:56:12.002342795Z [resource.labels.containerName: pgadapter] java -jar pgadapter.jar -p=my-project -i=my-instance -d=my-database -r=minSessions=50;maxSessions=100;numChannels=8 -x
ERROR 2025-06-03T22:56:12.013322598Z [resource.labels.containerName: pgadapter] Picked up JAVA_TOOL_OPTIONS: -Xmx768m -XX:+ExitOnOutOfMemoryError
INFO 2025-06-03T22:56:12.285596260Z [resource.labels.containerName: pgadapter] -- Starting PGAdapter version 0.48.0 --
INFO 2025-06-03T22:56:12.855447553Z [resource.labels.containerName: pgadapter] -- PostgreSQL version: 14.1 --
ERROR 2025-06-03T22:56:12.961277568Z [resource.labels.containerName: pgadapter] {}
INFO 2025-06-03T22:56:13.152664224Z [resource.labels.containerName: pgadapter] [2025-06-03 22:56:13.139] [INFO] (com.google.cloud.spanner.pgadapter.ProxyServer startServer): Server started on port 5432
INFO 2025-06-03T22:56:13.415414018Z [resource.labels.containerName: pgadapter] [2025-06-03 22:56:13.414] [INFO] (com.google.cloud.spanner.pgadapter.ConnectionHandler setThread): Connection handler with ID ConnectionHandler-0 created for client 127.0.0.1
```
**Logs** without `-XX:+ExitOnOutOfMemoryError`:
```
ERROR 2025-06-02T01:46:15.258980999Z [resource.labels.containerName: pgadapter] Exception in thread "ConnectionHandler-3604" java.lang.OutOfMemoryError: Java heap space at java.base/java.io.BufferedOutputStream.<init>(Unknown Source) at java.base/java.io.BufferedOutputStream.<init>(Unknown Source) at com.google.cloud.spanner.pgadapter.metadata.ConnectionMetadata.<init>(ConnectionMetadata.java:49) at com.google.cloud.spanner.pgadapter.ConnectionHandler.runConnection(ConnectionHandler.java:395) at com.google.cloud.spanner.pgadapter.ConnectionHandler.run(ConnectionHandler.java:349) at java.base/java.lang.Thread.runWith(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
INFO 2025-06-02T01:47:15.055153980Z [resource.labels.containerName: pgadapter] [2025-06-02 01:47:14.997] [INFO] (com.google.cloud.spanner.pgadapter.ConnectionHandler setThread): Connection handler with ID ConnectionHandler-3605 created for client 10.69.128.193
INFO 2025-06-02T01:47:15.056004276Z [resource.labels.containerName: pgadapter] [2025-06-02 01:47:15.055] [INFO] (com.google.cloud.spanner.pgadapter.ConnectionHandler run): [ConnectionHandler-3605]: [Run] Connection handler with ID ConnectionHandler-3605 starting for client 10.69.128.193 with thread Thread[#25403,ConnectionHandler-3605,5,main]
INFO 2025-06-02T01:47:15.304625930Z [resource.labels.containerName: pgadapter] [2025-06-02 01:47:15.302] [INFO] (com.google.cloud.spanner.pgadapter.ConnectionHandler runConnection): [ConnectionHandler-3605]: [RunConnection] Closing connection handler with ID ConnectionHandler-3605
INFO 2025-06-02T01:47:15.361293413Z [resource.labels.containerName: pgadapter] [2025-06-02 01:47:15.304] [INFO] (com.google.cloud.spanner.pgadapter.ConnectionHandler runConnection): [ConnectionHandler-3605]: [RunConnection] Connection handler with ID ConnectionHandler-3605 closed
ERROR 2025-06-02T01:47:15.361463908Z [resource.labels.containerName: pgadapter] Exception in thread "ConnectionHandler-3605" java.lang.OutOfMemoryError: Java heap space at java.base/java.io.BufferedInputStream.getBufIfOpen(Unknown Source) at java.base/java.io.BufferedInputStream.getBufIfOpen(Unknown Source) at java.base/java.io.BufferedInputStream.fill(Unknown Source) at java.base/java.io.BufferedInputStream.read1(Unknown Source) at java.base/java.io.BufferedInputStream.implRead(Unknown Source) at java.base/java.io.BufferedInputStream.read(Unknown Source) at java.base/java.io.DataInputStream.readFully(Unknown Source) at java.base/java.io.DataInputStream.readInt(Unknown Source) at com.google.cloud.spanner.pgadapter.wireprotocol.BootstrapMessage.create(BootstrapMessage.java:52) at com.google.cloud.spanner.pgadapter.ConnectionHandler.runConnection(ConnectionHandler.java:399) at com.google.cloud.spanner.pgadapter.ConnectionHandler.run(ConnectionHandler.java:349) at java.base/java.lang.Thread.runWith(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
ERROR 2025-06-02T01:47:17.637597756Z [resource.labels.containerName: pgadapter] Exception in thread "grpc-transport-21614" java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:47:36.977099523Z [resource.labels.containerName: pgadapter] [2025-06-02 01:47:36.899] [WARNING] (com.google.cloud.spanner.SpannerCloudMonitoringExporter exportSpannerClientMetrics): Failed to convert spanner metric data to cloud monitoring timeseries.
ERROR 2025-06-02T01:47:36.977153782Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:48:36.929792971Z [resource.labels.containerName: pgadapter] [2025-06-02 01:48:36.832] [WARNING] (com.google.cloud.spanner.SpannerCloudMonitoringExporter exportSpannerClientMetrics): Failed to convert spanner metric data to cloud monitoring timeseries.
ERROR 2025-06-02T01:48:36.929871454Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:48:54.614527817Z [resource.labels.containerName: pgadapter] Exception in thread "grpc-default-executor-87" java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:48:55.369079577Z [resource.labels.containerName: pgadapter] Exception in thread "grpc-default-executor-84" java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:48:57.822734931Z [resource.labels.containerName: pgadapter] [2025-06-02 01:48:57.821] [WARNING] (io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught): An exception 'java.lang.OutOfMemoryError: Java heap space' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
ERROR 2025-06-02T01:48:57.822781123Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:49:37.630196284Z [resource.labels.containerName: pgadapter] [2025-06-02 01:49:37.048] [SEVERE] (com.google.api.gax.rpc.Watchdog run): Caught throwable in periodic Watchdog run. Continuing.
ERROR 2025-06-02T01:49:37.630251194Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:49:38.292366839Z [resource.labels.containerName: pgadapter] [2025-06-02 01:49:37.048] [WARNING] (com.google.cloud.spanner.SpannerCloudMonitoringExporter exportSpannerClientMetrics): Failed to convert spanner metric data to cloud monitoring timeseries.
ERROR 2025-06-02T01:49:38.292413494Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:50:41.125942249Z [resource.labels.containerName: pgadapter] [2025-06-02 01:50:41.066] [SEVERE] (io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2Connection goAwayReceived): Caught Throwable from listener onGoAwayReceived.
ERROR 2025-06-02T01:50:41.126014048Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:50:42.555352728Z [resource.labels.containerName: pgadapter] [2025-06-02 01:50:42.437] [SEVERE] (io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2Connection goAwayReceived): Caught Throwable from listener onGoAwayReceived.
ERROR 2025-06-02T01:50:42.555417989Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:50:56.581618189Z [resource.labels.containerName: pgadapter] Exception in thread "spanner-postgres-adapter-proxy-listener" java.lang.OutOfMemoryError: Java heap space
ERROR 2025-06-02T01:51:08.004561671Z [resource.labels.containerName: pgadapter] [2025-06-02 01:51:07.780] [SEVERE] (io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2Connection goAwayReceived): Caught Throwable from listener onGoAwayReceived.
ERROR 2025-06-02T01:51:08.004624285Z [resource.labels.containerName: pgadapter] java.lang.OutOfMemoryError: Java heap space
```

Image

### PR DESCRIPTION
**Pull request by olavloite**
Remove ConnectionHandler instances from the CONNECTION_HANDLERS map when the connection is closed, regardless how the connection would be closed. Before this change, connection handlers that failed at startup, for example connection attempts from simple TCP probers, would not be cleaned up, and would cause a memory leak if repated TCP probes are executed.

Fixes #3402

### CODE REVIEW

File: src/main/java/com/google/cloud/spanner/pgadapter/ProxyServer.java [hunk 1]
```diff
@@ -65,6 +67,10 @@
 public class ProxyServer extends AbstractApiService {
 
   private static final Logger logger = Logger.getLogger(ProxyServer.class.getName());
+
+  @VisibleForTesting
+  static final Map<Integer, ConnectionHandler> CONNECTION_HANDLERS = new ConcurrentHashMap<>();
```
Comment (aakashanandg) [inline src/main/java/com/google/cloud/spanner/pgadapter/ProxyServer.java:72]: Can't we have this CONNECTION_HANDLERS map as a static entry inside the ConnectionHandler class itself? Any particular reason we are moving this to ProxyServer class?

Comment (olavloite) [reply src/main/java/com/google/cloud/spanner/pgadapter/ProxyServer.java:72]: The location could be any of the classes. I moved it here because I feel it more naturally belongs here. The `ProxyServer` is the owner of connection handlers.

In a follow-up PR, we probably even want to make this variable non-static (i.e. make it a regular member of `ProxyServer`).

**Review by aakashanandg — APPROVED** [review]
